package com.pillora.pillora.ui.theme

import androidx.compose.ui.graphics.Color

// Cores para o Tema Claro
val LightPrimary = Color(0xFF0061A4)
val LightOnPrimary = Color(0xFFFFFFFF)
val LightPrimaryContainer = Color(0xFFD1E4FF)
val LightOnPrimaryContainer = Color(0xFF001D36)
val LightSecondary = Color(0xFF535F70)
val LightOnSecondary = Color(0xFFFFFFFF)
val LightSecondaryContainer = Color(0xFFD6E4F7)
val LightOnSecondaryContainer = Color(0xFF0F1C2B)
val LightTertiary = Color(0xFF6B5778)
val LightOnTertiary = Color(0xFFFFFFFF)
val LightTertiaryContainer = Color(0xFFF3DAFF)
val LightOnTertiaryContainer = Color(0xFF251432)
val LightError = Color(0xFFBA1A1A)
val LightErrorContainer = Color(0xFFFFDAD6)
val LightOnError = Color(0xFFFFFFFF)
val LightOnErrorContainer = Color(0xFF410002)
val LightBackground = Color(0xFFFDFCFF)
val LightOnBackground = Color(0xFF1A1C1E)
val LightSurface = Color(0xFFFDFCFF)
val LightOnSurface = Color(0xFF1A1C1E)
val LightSurfaceVariant = Color(0xFFDFE2EB)
val LightOnSurfaceVariant = Color(0xFF43474E)
val LightOutline = Color(0xFF73777F)
val LightInverseOnSurface = Color(0xFFF1F0F4)
val LightInverseSurface = Color(0xFF2F3133)
val LightInversePrimary = Color(0xFF9ECAFF)
val LightSurfaceTint = Color(0xFF0061A4)
val LightOutlineVariant = Color(0xFFC3C6CF)
val LightScrim = Color(0xFF000000)
val LightSurfaceContainer = Color(0xFFECEFF4)

// Cores para o Tema Escuro
val DarkPrimary = Color(0xFF9ECAFF)
val DarkOnPrimary = Color(0xFF003258)
val DarkPrimaryContainer = Color(0xFF00497D)
val DarkOnPrimaryContainer = Color(0xFFD1E4FF)
val DarkSecondary = Color(0xFFBAC8DB)
val DarkOnSecondary = Color(0xFF253141)
val DarkSecondaryContainer = Color(0xFF3B4858)
val DarkOnSecondaryContainer = Color(0xFFD6E4F7)
val DarkTertiary = Color(0xFFD7BDE4)
val DarkOnTertiary = Color(0xFF3B2948)
val DarkTertiaryContainer = Color(0xFF523F60)
val DarkOnTertiaryContainer = Color(0xFFF3DAFF)
val DarkError = Color(0xFFFFB4AB)
val DarkErrorContainer = Color(0xFF93000A)
val DarkOnError = Color(0xFF690005)
val DarkOnErrorContainer = Color(0xFFFFDAD6)
val DarkBackground = Color(0xFF1A1C1E)
val DarkOnBackground = Color(0xFFE2E2E6)
val DarkSurface = Color(0xFF1A1C1E)
val DarkOnSurface = Color(0xFFE2E2E6)
val DarkSurfaceVariant = Color(0xFF43474E)
val DarkOnSurfaceVariant = Color(0xFFC3C6CF)
val DarkOutline = Color(0xFF8D9199)
val DarkInverseOnSurface = Color(0xFF1A1C1E)
val DarkInverseSurface = Color(0xFFE2E2E6)
val DarkInversePrimary = Color(0xFF0061A4)
val DarkSurfaceTint = Color(0xFF9ECAFF)
val DarkOutlineVariant = Color(0xFF43474E)
val DarkScrim = Color(0xFF000000)
val DarkSurfaceContainer = Color(0xFF222426)